# Code Generated by Sidekick is for learning and experimentation purposes only.
from pyspark.sql import SparkSession, functions as F

spark = SparkSession.builder.appName("stable-partition-rerun").getOrCreate()

TARGET_PATH = "/tmp/orders_target"

# Sample source data
data = [
    ("O1001", "C1", 120.0),
    ("O1002", "C2", 75.0),
    ("O1003", "C3", 40.0),
    ("O1004", "C4", 90.0),
    ("O1005", "C5", 30.0),
    ("O1006", "C6", 55.0),
    ("O1007", "C7", 200.0),
    ("O1008", "C8", 15.0),
    ("O1009", "C9", 99.0),
    ("O1010", "C10", 65.0),
]

df = spark.createDataFrame(data, ["order_id", "customer_id", "amount"])

# Step 1: Create a stable logical partition id from business key
df = df.withColumn(
    "stable_partition_id",
    F.pmod(F.xxhash64("order_id"), F.lit(10))
)

# See which rows belong to which logical partition
df.orderBy("stable_partition_id", "order_id").show(truncate=False)

# Step 2: Function to process one logical partition
def process_partition(partition_id, fail_partition_id=None):
    part_df = df.filter(F.col("stable_partition_id") == partition_id)

    count = part_df.count()
    print(f"Processing logical partition {partition_id}, rows={count}")

    # Simulate failure for demonstration
    if fail_partition_id is not None and partition_id == fail_partition_id:
        raise Exception(f"Simulated failure on partition {partition_id}")

    # Write only this partition to target
    # replaceWhere overwrites only the matching logical partition
    (
        part_df.write
        .format("delta")
        .mode("overwrite")
        .option("replaceWhere", f"stable_partition_id = {partition_id}")
        .partitionBy("stable_partition_id")
        .save(TARGET_PATH)
    )

# Step 3: Initial run across 10 logical partitions
failed_partitions = []

for pid in range(10):
    try:
        # simulate partition 3 failing
        process_partition(pid, fail_partition_id=3)
    except Exception as e:
        print(f"Partition {pid} failed: {e}")
        failed_partitions.append(pid)

print("Failed partitions:", failed_partitions)

# Step 4: Rerun only failed partitions
for pid in failed_partitions:
    try:
        process_partition(pid)
        print(f"Partition {pid} reprocessed successfully")
    except Exception as e:
        print(f"Partition {pid} failed again: {e}")

# Step 5: Validate target data
target_df = spark.read.format("delta").load(TARGET_PATH)
target_df.groupBy("stable_partition_id").count().orderBy("stable_partition_id").show()
target_df.orderBy("stable_partition_id", "order_id").show(truncate=False)
